FROM node:22-alpine

RUN apk add --no-cache \
    git \
    python3 \
    make \
    g++ \
    tzdata \
    haveged \
    pkgconfig \
    pixman-dev \
    cairo-dev \
    pango-dev \
    jpeg-dev \
    giflib-dev \
    librsvg-dev \
    ffmpeg

ENV TZ=Asia/Karachi
ENV NODE_ENV=production
ENV PORT=8000

WORKDIR /app

COPY package*.json ./
RUN npm install --production

COPY . .

EXPOSE 8000

CMD ["sh", "-c", "haveged -F & node keep-alive.js & node index.js"]
