services:
  - name: hyperwa-bot
    type: web
    instance_type: nano
    regions:
      - fra
    env:
      - key: NODE_ENV
        value: production
      - key: NODE_OPTIONS
        value: "--max-old-space-size=512"
    build:
      dockerfile: ./Dockerfile.koyeb
    ports:
      - port: 8000
        protocol: http
    scaling:
      min: 1
      max: 1
    routes:
      - path: /
        port: 8000
    health_checks:
      - http:
          path: /health
          port: 8000
          period_seconds: 30
          timeout_seconds: 10
